language: python
python:
- '3.6'

install:
- pip install -r requirements.txt
- pip install .

script:
- python tests/basic_test.py

env:
  global:
  - secure: PSJfSHHztOEhe++c8I0C7HSP9g4AtpYXOdTU5k6PUFoMfpXWzK+S9HYaY98YTriVb1bZQjJ6xUG6r0xrIpLwUPnaajPsPoiAZg4e393L6hy5pfhcpD5r8Q9p2N3gPLZ/ahYOeLWTHE+zsbJnoOkVSJeVn70U8rpr00fFu/yMq8T5QljmvjeDMNWZOKtI4ZBIdkQ/P6G0t7fFXFLvZG8rYps/flbW8/7zmXwRc3/P0crxVfUWQ0yYnSVZtPakGnB8mIZ4cR+Jtzg0pTE6W85852iP2I0cfO+DaJapPKmizWOXZOiJi0aShEgz6Q2amtbJWr/fQbFssyQEIksQQFwGoFGbK+8VOYgso3ZqsDRizBohxGK4MFyC/XkyaK/LKvMhsQn1YiYHkjU3PSDPTn7mPZm3gNTMQt5QvJN6ZvK7xc76Dl8GKKzWETeIE9fbCflZEVqpgQUwmONbKVzK1zEK2Yk6Z4gypbiwB/CroRqqr6qEQ67cM+zdrFhz9TIDPARvFjxWO4LP4t8MSd/1IUlTsw13K+mCZk4ENjQRvl1/iPbcTrAGxw1+PpkmbqovOAZy9rfex2GD+PIu4grX2oTkpLVuHdw2qrDU98CgQX0pPSJUQZh1ZbsnOD1I4ePrf2X24TV+tJW1DZUHcoEqKA2mMpZoFMkU7d6kApLVJqL9IpA=
  - secure: DELHCWYIbreVyj2QWjNJ6zFeX5eIj6CJ8txQHE+Hl0mWvOTUBZV0MvybV/it6CudGiTPfG2iDfCudHt07BAluR14L7W7HWV61BtVdA/dvjYDC96ujo46av4XqxTmuI9tGHJtHSI6b1S/mC9y7xIce/HQd1TFqPEC5y22Zvk7lV2OXTZZvTe9H4bfrIxn/njoZld2UN3wGI9Wgbh1fbMeEd5zYexgVRVnFRH6JQ43+ZY+K/dC8SYg0fpRwZ8gTWMolqjmtbKNkbsV8vVaVZ9LBwNDeWq/gkMLrfnILS19XaqsOIYh07vfstaTP72JVx72f4rT//uTQVSKNt4oY7bRT39IrEYmhVBcaZ/RpkTQN86um9gJbiYocyZ3fbjvwEaj7vt3ZEWA+gSrEoFAO7DiHf3kY/+uLZvg+segFwuSauGnl6ssq/jJuGUjOGbJ7A3ndnwL3fQdLO8LrDXuUmUBsAyB204LyM8DVNov+9wsyDcq6WU/R3JbfDFGuPj0WhBJAGOQy+frg3QPxifJiZoqiOMipZ2REF0FvzpNDEumD77jyI4h4kkdR1omUgYTx3l3d7O6oq3GqRW7ch8zeS78bGP/tPIEU71XfHw7ladLOX0hTWgawaQDdyPvaElwdMTUPvLc36zTQ+s8Lnc2reWK7BJJ4mhFiiNcebaSJvTp8ss=
